language: node_js
sudo: required
services:
  - docker
node_js:
  - 10.15.1

env:
  global:
    - SHA=$(git rev-parse HEAD)

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Test
      script:
        - echo "nothing"
    - stage: Deploy
      if: type = push AND branch IN (develop, master)
      script: skip
      deploy:
        provider: script
        script: bash ./deploy.sh
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^develop|master$
