apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-server
  labels:
    app: content-server
  namespace: content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-server
  template:
    metadata:
      labels:
        app: content-server
    spec:
      containers:
        - name: content-server
          image: 845778257277.dkr.ecr.ap-southeast-2.amazonaws.com/STAGE/content-server:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 4400
          envFrom:
            - secretRef:
                name: content-server
---
apiVersion: v1
kind: Service
metadata:
  name: content-server
  labels:
    app: content-server
    service: content-server
  namespace: content
spec:
  selector:
    app: content-server
  ports:
    - port: 4400
      targetPort: 4400
      name: http
